#Descargar ubuntu 18.04
FROM ubuntu:bionic

#Label about the custom image
LABEL maintainer="rocio@gmail.com"
LABEL version="0.1"
LABEL description="Imagen hola mundo con python3 y web.py"

#install packages
RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN pip install --upgrade pip
RUN pip3 install web.py

#Abrir el pueto
EXPOSE 8080

# mi contenedor es 1 y image version 1
#docker run -it --name prueba1 image:v1

#para correr es 
#docker build -t image:v1 . 
#docker images